version: "2"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    command: --auth
    volumes_from:
      - mongodata
  mongodata:
    image: tianon/true
    volumes:
      - ./data/db:/data/db
